import Link from "next/link";
import './globals.css'

import {revalidatePath} from "next/cache";
import Control from "./Control";
// import {useEffect, useState} from "react";


export const metadata = {
  title: 'Web tutorials',
  description: 'Generated by seo',
}



export default async function RootLayout({ children }) {
    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics',{cache:'no-store'})
    const topics = await resp.json()
  return (
    <html >
      <body>
      <h1><Link href={'/'}>WEB</Link></h1>
      <ol>
          {topics.map((topic)=>{
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
      </ol>
      {children}
        <Control/>
      </body>
    </html>
  )
}
